# Generated by Django 4.1.7 on 2023-03-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
    ]
