# Generated by Django 4.1.7 on 2023-03-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_favouritecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videouserviews',
            name='viewed_at',
        ),
        migrations.AlterField(
            model_name='coursecommentcomplaint',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('deception', 'deception'), ('offensive', 'offensive'), ('suicide', 'suicide'), ('other', 'other')], max_length=50, null=True, verbose_name='Complaint type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Payment date'),
        ),
    ]
