# Generated by Django 4.1.7 on 2023-03-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_pic_customuser_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar',
            new_name='profile_pic',
        ),
    ]
