# Generated by Django 4.1.7 on 2023-03-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='metro_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Metro'),
        ),
        migrations.AddField(
            model_name='info',
            name='metro_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Metro'),
        ),
        migrations.AddField(
            model_name='info',
            name='metro_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Metro'),
        ),
        migrations.AddField(
            model_name='rulesofusing',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='rulesofusing',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='rulesofusing',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='rulesofusing',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='rulesofusing',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='rulesofusing',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
